### ISSUE TITLE
How to obtain a Win32 version of md？

### ISSUE THREAD

**Issue by SaorenPu** [coin-or/Ipopt#766] opened 2024-05-24 02:08 UTC
For Windows users, What should I do if I now need the Win32 version, as only the Win64 md and mdd are provided in the Releases?
<img width="503" alt="1716516495247" src="https://github.com/coin-or/Ipopt/assets/124563760/27c699f8-0d0b-469f-aef1-34fb22a8e603">

**Comment by svigerske** [comment] 2024-05-27 14:16
Duplicate of #767.

**Closed as completed by svigerske** 2024-05-27 14:16 UTC
