### ISSUE TITLE
How to limit ipopt only use single thread?

### ISSUE THREAD

**Issue by ZedongPeng** [coin-or/Ipopt#691] opened 2023-08-28 21:56 UTC
According to the documentation, **MUMPS** inside **IPOPT** can use the multi-threading environment.

- Is there a way to limit **MUMPS** to use only one thread?
- Btw, I saw there is an option called `wsmp_num_threads`. Is this the correct option to set?
- I am using **IPOPT** through through **Pyomo**. Is it possible to set the thread option through **Pyomo**?

Many thanks.

https://github.com/coin-or/Ipopt/blob/11739c529d8265be6941a7c79cd3e0457270b74d/doc/faq.dox#L40-L44

**Comment by svigerske** [comment] 2023-08-29 06:24
I think, by default, Mumps uses only one thread. To enable parallelization (in the non-MPI version of Mumps), you would need to have Mumps build with OpenMP enabled and set the [`OMP_NUM_THREADS`](https://www.openmp.org/spec-html/5.0/openmpse50.html) environment variable, see also Section 3.12 of [the MUMPS documentation](https://mumps-solver.org/doc/userguide_5.6.1.pdf). There is currently no Ipopt option to set the number of threads for OpenMP in Mumps.

`wsmp_num_threads` is for setting the number of threads in WSMP, a different linear solver.

The FAQ entry you refer to is about running multiple Ipopt instances (and thus, possibly, multiple MUMPS instances) within the same process in parallel.

**Comment by ZedongPeng** [comment] 2023-08-29 15:12
Actually, I am doing some benchmarks with `IPOPT`. To make the benchmarks fair, I want to limit each benchmark to only one thread and run the benchmarks in parallel. In my impression, ipopt will only use one thread without any special options specified. However, when I used `IPOPT` recently, it automatically used multi-threads for some models. Is that possible? Or maybe my observation is wrong?

Many thanks for the response.

**Comment by ZedongPeng** [comment] 2023-08-30 20:23
My bad. The multi-thread computation comes from Cplex.
Thanks a lot for your help.

**Comment by ZedongPeng** [comment] 2023-09-11 23:13
Hi. Just a quick question. I saw the following command will use multiple threads. I am curious who might use multiple threads in the command. `Ipopt`, `pyomo` or `AMPL`?
Many thanks. @svigerske 
<img width="1518" alt="image" src="https://github.com/coin-or/Ipopt/assets/15854830/89946ecd-9514-471d-bfd8-03019680f0af">

**Comment by svigerske** [comment] 2023-09-12 07:55
From the command, it is Ipopt (or some of the subroutines called by Ipopt) that uses multiple cores.

Further, the Ipopt binary is part of MindtPy. So check with them what they included into this binary and under which situations it would use multiple threads.

**Comment by svigerske** [comment] 2023-11-01 15:05
Closing as could not reproduce.

**Closed as completed by svigerske** 2023-11-01 15:05 UTC
