### ISSUE TITLE
Stopping optimization in debug mode

### ISSUE THREAD

**Issue by Leersmaekers** [coin-or/Ipopt#661] opened 2023-04-23 09:41 UTC
I have an issue running Ipopt in `debug` mode. Somehow, after a normal function evaluation, Ipopt terminates with the message:

`EXIT: Stopping optimization at current point as requested by user.` (not asked to stop at the current point!)

If I run exactly the same program in `release` mode, there are no issues.

I'm not sure if the `ipopt.out` file will be helpful, but I attached it to be sure.

[ipopt.txt](https://github.com/coin-or/Ipopt/files/11303352/ipopt.txt)

**Comment by svigerske** [comment] 2023-04-23 13:49
The exit message should only come if the [intermediate callback](https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_CPP_ADDITIONAL) returns `false`.
Maybe you implemented that callback, but forgot a `return` statement.

**Comment by svigerske** [comment] 2023-11-01 15:12
Closing as could not reproduce, and no answer from reporter.

**Closed as completed by svigerske** 2023-11-01 15:12 UTC
