### ISSUE TITLE
ERROR: Solver (ipopt) returned non-zero return code (1)

### ISSUE THREAD

**Issue by JieZhu6** [coin-or/Ipopt#700] opened 2023-09-20 00:32 UTC
I'm getting an error while using ipopt to solve a model that contains constraints on the tanh function. The error log is as follows:

ERROR: Solver (ipopt) returned non-zero return code (1)
ERROR: Solver log: Ipopt 3.14.12:

    **************************************************************************
    **** This program contains Ipopt, a library for large-scale nonlinear
    optimization.
     Ipopt is released as open source code under the Eclipse Public License
     (EPL).
             For more information visit https://github.com/coin-or/Ipopt
    **************************************************************************
    ****

    This is Ipopt version 3.14.12, running with linear solver MUMPS 5.5.1.

    Number of nonzeros in equality constraint Jacobian...:        0 Number of
    nonzeros in inequality constraint Jacobian.:     3249 Number of nonzeros
    in Lagrangian Hessian.............:      745

    Error evaluating "var =" definition -1: can't evaluate tanh'(1152.63).

I don't know what the problem is that's causing this

**Comment by svigerske** [comment] 2023-09-20 08:17
Duplicate of #701.

**Closed as not planned by svigerske** 2023-09-20 08:17 UTC
